package Clase6.Pregunta1;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fruta.java
//  @ Date : 20/01/2022
//  @ Author : 
//
//
public class Fruta extends Producto {
	private int cantidad;
	private boolean esDulce;

	public Fruta(String codigo, String nombre, Double precio) {
		super(codigo, nombre, precio);
	}

	public Fruta(String codigo, String nombre, Double precio, int cantidad, boolean esDulce) {
		super(codigo, nombre, precio);
		this.cantidad = cantidad;
		this.esDulce = esDulce;
	}

	public double calcularValor() {
	 return cantidad * super.getPrecio();
	}

	public int getCantidad() {
		return cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public boolean isEsDulce() {
		return esDulce;
	}

	public void setEsDulce(boolean esDulce) {
		this.esDulce = esDulce;
	}
}
