package Clase6.Pregunta1;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Liquido.java
//  @ Date : 20/01/2022
//  @ Author : 
//
//
public class Liquido extends Producto {
	private double contenido;
	private String marca;

	public Liquido(String codigo, String nombre, Double precio) {
		super(codigo, nombre, precio);
	}

	public Liquido(String codigo, String nombre, Double precio, double contenido, String marca) {
		super(codigo, nombre, precio);
		this.contenido = contenido;
		this.marca = marca;
	}

	public double calcularValor() {
		if(contenido > 50){
			return getPrecio();
		}
		else{
			return 0;
		}
	}

	public double getContenido() {
		return contenido;
	}

	public void setContenido(double contenido) {
		this.contenido = contenido;
	}

	public String getMarca() {
		return marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}
}
