package Clase6.Pregunta1;//

import java.util.ArrayList;
import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Refrigeradora.java
//  @ Date : 20/01/2022
//  @ Author : 
//
//
public class Refrigeradora {

	private List<Producto> productos;

	public Refrigeradora(List<Producto> productos) {
		this.productos = productos;
	}

	public Refrigeradora() {
		this.productos = new ArrayList<>();
	}

	public List<Producto> getProductos(){
		return productos;
	}

	public void registrarProducto(Producto producto) {
		productos.add(producto);
	}
	
	public boolean verificarExisteFrutaDulce() {
		for (Producto prod: this.productos){
			//Verificar que sea una Fruta y que sea Dulce
			if((prod instanceof Fruta) && ((Fruta) prod).isEsDulce()){
				return true;
			}
		}
		return false;
	}
	
	public double calcularValorTotalProductos() {
		double valorTotal = 0;
		for(Producto prod: productos){
			valorTotal = valorTotal + prod.calcularValor();
		}
		return valorTotal;
	}
}
