package Seleccion;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : medico.java
//  @ Date : 13/01/2022
//  @ Author : 
//
//

public class Medico extends Seleccion {
	private String colegiatura;
	private String especialidad;

	public Medico(String dni, String apellidos, String nombres, Integer edad, String colegiatura, String especialidad) {
		super(dni, apellidos, nombres, edad);
		this.colegiatura = colegiatura;
		this.especialidad = especialidad;
	}

	public void monitorearEstadoSalud() {
		System.out.println("Monitoreando el estado de salud de la selección.");
	}

	public static void main(String[] args) {
		Entrenador entrenador1 = new Entrenador("40205632", "Ancco", "Jose", 25, "FPF001");
		Futbolista futbolista = new Futbolista("41698745", "Perea", "Luis", 22, 10, "Medio");
		Medico medico = new Medico("10235687", "Alva", "Jorge", 60, "45874", "Interna");

		//Completar:
		//Los eventos comunes recorrerlos en un tipo de coleccion: ArrayList, List. (todos)
		//Los eventos particulares mostrar todas sus operaciones.

	}

	public String getColegiatura() {
		return colegiatura;
	}

	public void setColegiatura(String colegiatura) {
		this.colegiatura = colegiatura;
	}

	public String getEspecialidad() {
		return especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}
}
