package Seleccion;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Herencia
//  @ File Name : seleccion.java
//  @ Date : 13/01/2022
//  @ Author : David Malca
//	@ Descripcion: Implementacion de una seleccion de futbol
//

public class Seleccion {
	private String dni;
	private String apellidos;
	private String nombres;
	private Integer edad;

	public Seleccion(String dni, String apellidos, String nombres, Integer edad) {
		this.dni = dni;
		this.apellidos = apellidos;
		this.nombres = nombres;
		this.edad = edad;
	}

	public Seleccion() {
	}

	public void viajar() {
		System.out.println("Viajando.");
	}
	
	public void concentrar() {
		System.out.println("En concentración.");
	}

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public Integer getEdad() {
		return edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}
}
