package Taller1.Ejercicio1;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Diputado.java
//  @ Date : 22/01/2022
//  @ Author : 
//
//
public class Diputado extends Legislador {

    public Diputado() {
    }

    public Diputado(String dni, String nombres, String apellidos, String departamento) {
        super(dni, nombres, apellidos, departamento);
    }

    public Diputado(String dni, String nombres, String apellidos) {
        super(dni, nombres, apellidos);
    }

    @Override
    public String mostrarCamaraTrabaja() {
        return "Trabaja en la Cámara de Diputados.";
    }
}
