package Taller1.Ejercicio1;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Legislador.java
//  @ Date : 22/01/2022
//  @ Author : 
//
//
public abstract class Legislador extends Persona {
	private String departamento;

	public Legislador() {
	}

	public Legislador(String dni, String nombres, String apellidos, String departamento) {
		super(dni, nombres, apellidos);
		this.departamento = departamento;
	}

	public Legislador(String dni, String nombres, String apellidos) {
		super(dni, nombres, apellidos);
	}

	//Metodo abstracto: 1. No se debe implementar en la clase padre. 2. Necesariamente debe implementarse en las clases hijas
	public abstract String mostrarCamaraTrabaja();

	public String mostrarDatos(){
		return super.mostrarDatos() +  ", Departamento al que representa: " + departamento;
	}
}
