package Taller1.Ejercicio1;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.java
//  @ Date : 22/01/2022
//  @ Author : 
//
//
public class Persona {
	private String dni;
	private String nombres;
	private String apellidos;

	public Persona(String dni, String nombres, String apellidos) {
		this.dni = dni;
		this.nombres = nombres;
		this.apellidos = apellidos;
	}

	public Persona() {
	}

	public String mostrarDatos() {
		return "DNI: "+ dni + ", Nombre: " + nombres + ", Apellidos: " + apellidos;
	}

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}
}
