package Taller1.Ejercicio1;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Senador.java
//  @ Date : 22/01/2022
//  @ Author : 
//
//
public class Senador extends Legislador {

    public Senador() {
    }

    public Senador(String dni, String nombres, String apellidos, String departamento) {
        super(dni, nombres, apellidos, departamento);
    }

    public Senador(String dni, String nombres, String apellidos) {
        super(dni, nombres, apellidos);
    }

    @Override
    public String mostrarCamaraTrabaja() {
        return "Trabaja en la Cámara de Senadores";
    }
}
