package Seleccion;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : entrenador.java
//  @ Date : 13/01/2022
//  @ Author : 
//
//

public class Entrenador extends Seleccion {
	private String codigoFederacion;

	public Entrenador(String dni, String apellidos, String nombres, Integer edad, String codigoFederacion) {
		super(dni, apellidos, nombres, edad);
		this.codigoFederacion = codigoFederacion;
	}

	public void dirigirEntrenamiento() {
		System.out.println("Dirigiendo el entrenamiento.");
	}
	
	public void dirigirPartido() {
		System.out.println("Dirigiendo el partido.");
	}

	public String getCodigoFederacion() {
		return codigoFederacion;
	}

	public void setCodigoFederacion(String codigoFederacion) {
		this.codigoFederacion = codigoFederacion;
	}
}
