package Seleccion;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : futbolista.java
//  @ Date : 13/01/2022
//  @ Author : 
//
//

public class Futbolista extends Seleccion {
	private Integer numeracion;
	private String posicion;

	public Futbolista(String dni, String apellidos, String nombres, Integer edad, Integer numeracion, String posicion) {
		super(dni, apellidos, nombres, edad);
		this.numeracion = numeracion;
		this.posicion = posicion;
	}

	public void entrenar() {
		System.out.println("Entrenando para el próximo partido.");
	}
	
	public void jugarPartido() {
		System.out.println("Jugando un partido.");
	}

	public Integer getNumeracion() {
		return numeracion;
	}

	public void setNumeracion(Integer numeracion) {
		this.numeracion = numeracion;
	}

	public String getPosicion() {
		return posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}
}
