package Aeropuerto;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aerolinea.java
//  @ Date : 1/02/2022
//  @ Author : 
//
//
public class Aerolinea {
	private Vuelo vuelos;
	public void registrarVuelo() {
	
	}
	
	public void mostrarListaVuelosModeloAvion() {
	
	}
}
