package Aeropuerto;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asiento.java
//  @ Date : 1/02/2022
//  @ Author : 
//
//
public class Asiento {
	private int numero;
	private String letra;
	public void calcularPrecioBase() {
	
	}
	
	public void calcularFactor() {
	
	}
	
	public void calcularPrecioFinal() {
	
	}
}
