package Aeropuerto;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Avion.java
//  @ Date : 1/02/2022
//  @ Author : 
//
//
public class Avion {
	private String modelo;
	private Asiento asientos;
	public void registrarAsiento() {
	
	}
}
