package Aeropuerto;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vuelo.java
//  @ Date : 1/02/2022
//  @ Author : 
//
//
public class Vuelo {
	private String codigo;
	private Avion avion;
	private String origen;
	private String destino;
	public void asignarAvion() {
	
	}
	
	public void validarAvionModelo() {
	
	}
}
