package Cine;//

import java.util.ArrayList;
import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cine.java
//  @ Date : 25/01/2022
//  @ Author : 
//
//
public class Cine {
	private List<Sala> salas;

	public Cine(List<Sala> salas) {
		this.salas = salas;
	}

	public Cine() {
		this.salas = new ArrayList<>();
	}

	public void registrarSala(String codigo, Pelicula pelicula) {
		Sala sala = new Sala(codigo, pelicula);
		salas.add(sala);
	}
	
	public void eliminarSala() {
	
	}
	
	public Sala buscarSalaPorCodigo(String codigo) {
		for(Sala sala:salas){
			if(sala.getCodigo().equals(codigo)){
				return sala;
			}
		}
		return null;
	}
	
	public Sala obtenerSalaMayorVentaAsiento4D() {
		Sala salaMaxVenta4D = null;
		double maxVenta = 0;
		for(Sala sala:salas){
			if(sala.validarAsiento4D() && sala.calcularMontoTotalVenta() > maxVenta){
				//Aqui debo asignar los valores que cumplen la condición
				maxVenta = sala.calcularMontoTotalVenta();
				salaMaxVenta4D = sala;
			}
		}
		return salaMaxVenta4D;
	}
	
	public void asignarAsientoASala(String codigo, int fila, String letra, String categoria) {
		Sala sala = buscarSalaPorCodigo(codigo);
		//Si encuentro la sala recién puedo asignar el asiento
		sala.registrarAsiento(fila, letra, categoria);
	}

	public List<Sala> getSalas() {
		return salas;
	}

	public void setSalas(List<Sala> salas) {
		this.salas = salas;
	}
}
