package Cine;//

import java.util.ArrayList;
import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sala.java
//  @ Date : 25/01/2022
//  @ Author : 
//
//
public class Sala {
	private String codigo;
	private List<Asiento> asientos;
	private Pelicula pelicula;

	public Sala(String codigo, List<Asiento> asientos, Pelicula pelicula) {
		this.codigo = codigo;
		this.asientos = asientos;
		this.pelicula = pelicula;
	}

	public Sala() {
	}

	public Sala(String codigo, Pelicula pelicula) {
		this.codigo = codigo;
		this.pelicula = pelicula;
		this.asientos = new ArrayList<>();
	}

	public void registrarAsiento(int fila, String letra, String categoria) {
		Asiento asiento = new Asiento(fila, letra, categoria);
		//Agrego el asiento recibido por parametro a mi listado
		asientos.add(asiento);
	}
	@Override
	public String toString() {
	return "Sala {" + "Asientos = "+ asientos + ", pelicula = " +pelicula + ", Monto total = S/ " + calcularMontoTotalVenta() +"}";
	}
	
	public boolean validarAsiento4D() {
		for(Asiento asiento:asientos){
			if(asiento.getCategoria().equals("4DX")) {
				return true;
			}
		}
		return false;
	}

	//Calculo el monto total de la venta de los asientos de la sala
	public double calcularMontoTotalVenta() {
		double montoTotal = 0;
		for (Asiento asiento: asientos){
			montoTotal = montoTotal + asiento.calcularPrecio();
		}
		return montoTotal;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public List<Asiento> getAsientos() {
		return asientos;
	}

	public void setAsientos(List<Asiento> asientos) {
		this.asientos = asientos;
	}

	public Pelicula getPelicula() {
		return pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}
}
