package Cine;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asiento.java
//  @ Date : 25/01/2022
//  @ Author : 
//
//
public class Asiento {
	private int fila;
	private String letra;
	private String categoria;

	public Asiento(int fila, String letra, String categoria) {
		this.fila = fila;
		this.letra = letra;
		this.categoria = categoria;
	}

	public Asiento() {
	}

	public double calcularPrecio() {
		if(this.categoria.equals("Regular")){
			return 20;
		}
		else if(this.categoria.equals("4DX")){
			return 45;
		}
		else {
			return 0;
		}
	}

	public int getFila() {
		return fila;
	}

	public void setFila(int fila) {
		this.fila = fila;
	}

	public String getLetra() {
		return letra;
	}

	public void setLetra(String letra) {
		this.letra = letra;
	}

	public String getCategoria() {
		return categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
}
