package Cine;//

import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cine.java
//  @ Date : 25/01/2022
//  @ Author : 
//
//
public class Cine {
	private List<Sala> salas;

	public Cine(List<Sala> salas) {
		this.salas = salas;
	}

	public Cine() {
	}

	public void registrarSala() {
	
	}
	
	public void eliminarSala() {
	
	}
	
	public void buscarSalaPorCodigo() {
	
	}
	
	public void obtenerSalaMayorVentaAsiento4D() {
	
	}
	
	public void asignarPelicula() {
	
	}

	public List<Sala> getSalas() {
		return salas;
	}

	public void setSalas(List<Sala> salas) {
		this.salas = salas;
	}
}
