package Cine;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pelicula.java
//  @ Date : 25/01/2022
//  @ Author : 
//
//
public class Pelicula {
	private String nombre;

	public Pelicula(String nombre) {
		this.nombre = nombre;
	}

	public Pelicula() {
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
