package Cine;//

import java.util.List;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sala.java
//  @ Date : 25/01/2022
//  @ Author : 
//
//
public class Sala {
	private String codigo;
	private List<Asiento> asientos;
	private Pelicula pelicula;

	public Sala(String codigo, List<Asiento> asientos, Pelicula pelicula) {
		this.codigo = codigo;
		this.asientos = asientos;
		this.pelicula = pelicula;
	}

	public Sala() {
	}

	public void registrarAsiento() {
	
	}
	
	public void mostrarInformacion() {
	
	}
	
	public void validarAsiento4D() {
	
	}
	
	public void calcularMontoTotalVenta() {
	
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public List<Asiento> getAsientos() {
		return asientos;
	}

	public void setAsientos(List<Asiento> asientos) {
		this.asientos = asientos;
	}

	public Pelicula getPelicula() {
		return pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}
}
